name: deploy to production
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.9]

    steps:
      - name: read code
        uses: actions/checkout@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: npm install and build
        run: |
          npm install
          npm run docs:build
          ls
          pwd
          ls -R ./docs/ || echo "Dist directory not found"
          ls -R ./docs/.vitepress/ || echo "Dist directory not found"
        env:
          CI: true
          
      - name: Deploy
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ./docs/.vitepress/dist/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_KEY }}
          remote_path: ${{ secrets.SERVER_WORKDIR }}

